# Generated by Django 3.0.7 on 2020-06-15 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goodsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Size',
            new_name='Time',
        ),
        migrations.RenameField(
            model_name='time',
            old_name='sname',
            new_name='tname',
        ),
    ]
